improve helm template

diff --git a/.github/workflows/deploy-and-test-cluster.yml b/.github/workflows/deploy-and-test-cluster.yml
--- a/.github/workflows/deploy-and-test-cluster.yml
+++ b/.github/workflows/deploy-and-test-cluster.yml
@@ -34,7 +34,7 @@ jobs:
     steps:
       - name: Show Version
         run: |
-          echo "Deploying Applicaion with Version: ${{ inputs.version }}, Helm chart version: ${{ inputs.deployed-by-build }}, to namespace ${{ inputs.namespace }}"
+          echo "Deploying Version: ${{ inputs.version }}"
           echo "Deployment triggered by workflow ${{ inputs.deployed-by-workflow }}. Run number: ${{ inputs.deployed-by-build }}"
 
       - name: Check out the repository
@@ -77,80 +77,43 @@ jobs:
     steps:
       - name: Show Version
         run: |
-          echo "Deploying Version: ${{ inputs.version }}"
+          echo "Deploying Applicaion with Version: ${{ inputs.version }}, Helm chart version: ${{ inputs.helm-chart-version }}, to namespace ${{ inputs.namespace }}"
           echo "Deployment triggered by workflow ${{ inputs.deployed-by-workflow }}. Run number: ${{ inputs.deployed-by-build }}"
 
       - name: Check out the repository
         uses: actions/checkout@v4
-
-      - name: Set up java 21
-        uses: actions/setup-java@v4
-        with:
-          java-version: 21
-          distribution: 'temurin'
-          cache: 'maven'
-          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml.
-          settings-path: ${{ github.workspace }} # location for the settings.xml file
-
-      - name: Get Helm Version
-        id: get_helm_version
-        run: |
-          set -o pipefail    # don't hide errors within pipes
-          set -o nounset     # abort on unbound variable
-          set -o errexit     # abort on nonzero exit status
-          BRANCH_NAME=${{ github.ref_name }}
-          if [[ "${BRANCH_NAME}" == "master" ||  "${BRANCH_NAME}" == "main" ]]; then
-            echo "::notice:: ### Build of Master."
-          else
-            echo "::notice:: ### Build of Feature Branch."
-            mvn -B versions:set -e -DnewVersion="${{ inputs.version }}"
-          fi
-          mvn -B -e initialize -s $GITHUB_WORKSPACE/settings.xml
-          HELM_CHART_VERSION=$(grep 'helm.chart.version' target/helm.properties | cut -d'=' -f2)
-          echo "helm chart version is: $HELM_CHART_VERSION"
-          echo "HELM_CHART_VERSION=$HELM_CHART_VERSION" >> $GITHUB_OUTPUT
 
       - name: Create k8s Kind Cluster
         uses: helm/kind-action@v1.12.0
 
       - name: Pull Helm Chart
         env:
-          HELM_CHART_VERSION: ${{ steps.get_helm_version.outputs.HELM_CHART_VERSION }}
+          HELM_CHART_VERSION: ${{ inputs.helm-chart-version }}
         run: |
-          if [ -z "$HELM_CHART_VERSION" ]; then
-            echo "Error: HELM_CHART_VERSION is not set. Aborting."
-            exit 1
-          fi
-          
-          mvn helm dry-run
-          NAMESPACE=$(helm template spring-6-project-template ./spring-6-project-template | grep -m 1 'namespace:' | awk '{print $2}')
-          if [ -z "$NAMESPACE" ]; then
-            NAMESPACE="default"
-          fi
-          
-          echo "### Application deployed to namespace: $NAMESPACE"
-          echo "NAMESPACE=$NAMESPACE" >> $GITHUB_OUTPUT
-          
           echo "Pulling Helm Chart Version: $HELM_CHART_VERSION"
           helm pull oci://registry-1.docker.io/domboeckli/spring-6-project-template --version "$HELM_CHART_VERSION"
           tar -xvf spring-6-project-template-*.tgz  
 
       - name: Deploy application with Helm
+        env:
+          APP_VERSION: ${{ inputs.version }}
         run: |
           # Install/upgrade the Helm chart
+          echo "Deploying Application: $APP_VERSION"
           helm upgrade --install spring-6-project-template ./spring-6-project-template \
-          --set image.tag=${{ inputs.version }} \
+          --set image.tag=${APP_VERSION} \
           --wait --timeout 5m \
           --debug
-          
 
       - name: Wait for Pods to be ready
+        env:
+          NAMESPACE: ${{ inputs.namespace }}
         run: |
-          if ! kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=spring-6-project-template -n spring-6-project-template --timeout=180s; then
-            POD_NAME=$(kubectl get pods -l app.kubernetes.io/name=spring-6-project-template -o jsonpath="{.items[0].metadata.name}" -n spring-6-project-template)
-            kubectl logs $POD_NAME -n spring-6-project-template
+          if ! kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=spring-6-project-template -n $NAMESPACE --timeout=180s; then
+            POD_NAME=$(kubectl get pods -l app.kubernetes.io/name=spring-6-project-template -o jsonpath="{.items[0].metadata.name}" -n $NAMESPACE)
+            kubectl logs $POD_NAME -n $NAMESPACE
             echo "Describing the pod:"
-            kubectl describe pod $POD_NAME -n spring-6-project-template
+            kubectl describe pod $POD_NAME -n $NAMESPACE
             exit 1
           fi
           BUILD_LINK="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ inputs.deployed-by-build }}"
@@ -158,6 +121,8 @@ jobs:
           echo "::notice:: ### Deployment triggered by workflow ${{ inputs.deployed-by-workflow }}. Run number: ${{ inputs.deployed-by-build }}: $BUILD_LINK"
 
       - name: Display Deployment Information
+        env:
+          NAMESPACE: ${{ inputs.namespace }}
         if: always()
         run: |
           echo "Deployment Information:"
@@ -178,18 +143,18 @@ jobs:
           kubectl get events --sort-by=.metadata.creationTimestamp --all-namespaces
           
           echo "--- Show Logs (if pods exist)"
-          PODS=$(kubectl get pods -l app.kubernetes.io/name=spring-6-project-template -o jsonpath="{.items[*].metadata.name}" -n spring-6-project-template)
+          PODS=$(kubectl get pods -l app.kubernetes.io/name=spring-6-project-template -o jsonpath="{.items[*].metadata.name}" -n $NAMESPACE)
           if [ -n "$PODS" ]; then
             for POD in $PODS; do
               echo "Logs for pod $POD:"
-              kubectl logs $POD -n spring-6-project-template --all-containers
+              kubectl logs $POD -n $NAMESPACE --all-containers
             done
           else
-            echo "No pods found with label app.kubernetes.io/name=spring-6-project-template in spring-6-project-template namespace"
-            echo "Listing all pods in spring-6-project-template namespace:"
-            kubectl get pods -n spring-6-project-template
+            echo "No pods found with label app.kubernetes.io/name=spring-6-project-template in $NAMESPACE namespace"
+            echo "Listing all pods in $NAMESPACE namespace:"
+            kubectl get pods -n $NAMESPACE
           fi
           
           echo "--- Describe Helm release"
-          helm get manifest spring-6-project-template -n spring-6-project-template || echo "Helm release not found"
+          helm get manifest spring-6-project-template -n $NAMESPACE || echo "Helm release not found in namespace $NAMESPACE"
 
