finalize

diff --git a/.github/workflows/deploy-and-test-cluster.yml b/.github/workflows/deploy-and-test-cluster.yml
--- a/.github/workflows/deploy-and-test-cluster.yml
+++ b/.github/workflows/deploy-and-test-cluster.yml
@@ -75,6 +75,15 @@ jobs:
       - name: Check out the repository
         uses: actions/checkout@v4
 
+      - name: Run Maven Build
+        run: |
+          set -o pipefail    # don't hide errors within pipes
+          set -o nounset     # abort on unbound variable
+          set -o errexit     # abort on nonzero exit status
+          mvn -B -e initialize
+          HELM_CHART_VERSION=$(mvn help:evaluate -Dexpression=helm.chart.version -q -DforceStdout)
+          echo "helm version is: $HELM_CHART_VERSION"
+
       - name: Create k8s Kind Cluster
         uses: helm/kind-action@v1.12.0
 
