fix sonar build

diff --git a/.github/workflows/maven-build.yml b/.github/workflows/maven-build.yml
--- a/.github/workflows/maven-build.yml
+++ b/.github/workflows/maven-build.yml
@@ -6,7 +6,7 @@ on:
   push:
     branches: [ "main", "master", "feature/**", "release/**" ]
   pull_request:
-    branches: [ "main", "master" ]  
+    branches: [ "main", "master" ]
   schedule:
     - cron: '5 2 * * *' # daily at 2:05
 jobs:
@@ -65,8 +65,8 @@ jobs:
           echo ":maple_leaf: Artifact ID: ${{ steps.set_version.outputs.ARTIFACT_ID }}" >> $GITHUB_STEP_SUMMARY
           echo ":maple_leaf: Original Maven version: ${{ steps.set_version.outputs.MVN_VERSION }}" >> $GITHUB_STEP_SUMMARY
           echo ":cactus: Calculated Maven Version: ${{ steps.set_version.outputs.BRANCH_MVN_VERSION }}" >> $GITHUB_STEP_SUMMARY
-          
-
+  
+  
   build:
     runs-on: ubuntu-latest
 
@@ -83,7 +83,7 @@ jobs:
 
     steps:
       - uses: actions/checkout@v4
-        
+
       - name: Set up java 21
         uses: actions/setup-java@v4
         with:
@@ -135,18 +135,10 @@ jobs:
           fi
           mvn -B -e deploy -s $GITHUB_WORKSPACE/settings.xml
           
-      - name: Cache produced build target
-        uses: actions/cache@v4
-        with:
-          path: ./target
-          key: ${{ runner.os }}-cache-${{ github.sha }}
-          
-      
-          
   analyze:
     runs-on: ubuntu-latest
-    needs: [build,setup]
-    
+    needs: [ setup ]
+        
     permissions:
       contents: read
       packages: write
@@ -154,12 +146,12 @@ jobs:
       checks: write
       pull-requests: write
       actions: read
-    
+
     steps:
       - uses: actions/checkout@v4
         with:
-          fetch-depth: 0
-
+          fetch-depth: 0    
+          
       - name: Set up java 21
         uses: actions/setup-java@v4
         with:
@@ -167,26 +159,46 @@ jobs:
           distribution: 'temurin'
           cache: 'maven'
           server-id: github # Value of the distributionManagement/repository/id field of the pom.xml.
-          settings-path: ${{ github.workspace }} # location for the settings.xml file  
-        
-      - name: Restore cache
-        uses: actions/cache@v4
-        with:
-          path: ./target
-          key: ${{ runner.os }}-cache-${{ github.sha }}
-      - name: Read cached data
+          settings-path: ${{ github.workspace }} # location for the settings.xml file       
+
+      - name: Run Maven Build
+        env:
+          GITHUB_ACTOR: ${{ github.actor }}
+          GITHUB_TOKEN: ${{ github.token }}
+          BRANCH_MVN_VERSION: ${{needs.setup.outputs.BRANCH_MVN_VERSION}}
+          BRANCH_NAME: ${{needs.setup.outputs.BRANCH_NAME}}
+          DOCKER_USER: ${{ secrets.DOCKER_USER }}
+          DOCKER_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
         run: |
-          echo "showing restore cache with tree"
-          tree
-          
+          set -o pipefail    # don't hide errors within pipes
+          set -o nounset     # abort on unbound variable
+          set -o errexit     # abort on nonzero exit status
+
+          # Check if required parameters are set
+          required_params=("GITHUB_ACTOR" "GITHUB_TOKEN" "BRANCH_MVN_VERSION" "BRANCH_NAME" "DOCKER_USER" "DOCKER_TOKEN")
+          for param in "${required_params[@]}"; do
+            if [ -z "${!param}" ]; then
+              echo "::error::Required parameter $param is not set"
+              exit 1
+            fi
+          done
+
+          if [[ "${BRANCH_NAME}" == "master" ||  "${BRANCH_NAME}" == "main" ]]; then
+            echo "::notice:: ### Build of Master. Version: $BRANCH_MVN_VERSION"
+          else
+            echo "::notice:: ### Build of Feature Branch ${BRANCH_NAME}. Version: $BRANCH_MVN_VERSION"
+            mvn -B versions:set -e -DnewVersion="$BRANCH_MVN_VERSION"
+          fi
+          mvn -B -e install -Dskip.start.stop.springboot=true -s $GITHUB_WORKSPACE/settings.xml	
+      
       - name: Publish Test Results
         uses: EnricoMi/publish-unit-test-result-action@v2
         if: always()
         with:
           files: |
             ./target/surefire-reports/TEST-*.xml
-            ./target/failsafe-reports/TEST-*.xml   
-            
+            ./target/failsafe-reports/TEST-*.xml
+      
       - name: analyze
         env:
           GITHUB_ACTOR: ${{ github.actor }}
@@ -198,7 +210,7 @@ jobs:
           DOCKER_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
           ORGANIZATION: ${{needs.setup.outputs.ORGANIZATION}}
           ARTIFACT_ID: ${{needs.setup.outputs.ARTIFACT_ID}}
-        
+          
         run: |
           set -o pipefail    # don't hide errors within pipes
           set -o nounset     # abort on unbound variable
@@ -233,4 +245,5 @@ jobs:
                   -Dsonar.projectKey="${ORGANIZATION}_${ARTIFACT_ID}" \
                   -Dsonar.branch.name=${BRANCH_NAME} \
                   -Dsonar.branch.target=master
-          fi           
+          fi 
+        
