improve helm template

diff --git a/.github/workflows/maven-build.yml b/.github/workflows/maven-build.yml
--- a/.github/workflows/maven-build.yml
+++ b/.github/workflows/maven-build.yml
@@ -193,6 +193,24 @@ jobs:
          path: |
            target/failsafe-reports/
            target/surefire-reports/
+
+      - name: get helm variables
+        id: get_helm_version
+        run: |
+          set -o pipefail    # don't hide errors within pipes
+          set -o nounset     # abort on unbound variable
+          set -o errexit     # abort on nonzero exit status
+          
+          HELM_CHART_VERSION=$(grep 'helm.chart.version' target/helm.properties | cut -d'=' -f2)
+          echo "### helm chart version is: $HELM_CHART_VERSION"
+          echo "HELM_CHART_VERSION=$HELM_CHART_VERSION" >> $GITHUB_OUTPUT
+          
+          NAMESPACE=$(helm template spring-6-project-template ./target/helm-templated/spring-6-project-template | grep -m 1 'namespace:' | awk '{print $2}')
+          if [ -z "$NAMESPACE" ]; then
+            NAMESPACE="default"
+          fi
+          echo "### Application is using namespace: $NAMESPACE"
+          echo "NAMESPACE=$NAMESPACE" >> $GITHUB_OUTPUT
           
   analyze:
     runs-on: ubuntu-latest
