use cache for sonar

diff --git a/.github/workflows/maven-build.yml b/.github/workflows/maven-build.yml
--- a/.github/workflows/maven-build.yml
+++ b/.github/workflows/maven-build.yml
@@ -141,58 +141,11 @@ jobs:
           path: ./target
           key: ${{ runner.os }}-cache-${{ github.sha }}
           
-      # TODO: MOVE TO SEPARATE JOB. SEE TICKET https://github.com/dboeckli/spring-6-project-template/issues/26
-      - name: analyze
-        env:
-          GITHUB_ACTOR: ${{ github.actor }}
-          GITHUB_TOKEN: ${{ github.token }}
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-          BRANCH_MVN_VERSION: ${{needs.setup.outputs.BRANCH_MVN_VERSION}}
-          BRANCH_NAME: ${{needs.setup.outputs.BRANCH_NAME}}
-          DOCKER_USER: ${{ secrets.DOCKER_USER }}
-          DOCKER_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
-          ORGANIZATION: ${{needs.setup.outputs.ORGANIZATION}}
-          ARTIFACT_ID: ${{needs.setup.outputs.ARTIFACT_ID}}
-          
-        run: |
-          set -o pipefail    # don't hide errors within pipes
-          set -o nounset     # abort on unbound variable
-          set -o errexit     # abort on nonzero exit status
-          
-          # Check if required parameters are set
-          required_params=("SONAR_TOKEN")
-          for param in "${required_params[@]}"; do
-            if [ -z "${!param}" ]; then
-              echo "::error::Required parameter $param is not set"
-              exit 1
-            fi
-          done
-          
-          if [[ "${BRANCH_NAME}" == "master" ||  "${BRANCH_NAME}" == "main" ]]; then
-            mvn -B sonar:sonar \
-                  -s $GITHUB_WORKSPACE/settings.xml \
-                  -Dsonar.token=${SONAR_TOKEN} \
-                  -Dsonar.host.url=https://sonarcloud.io \
-                  -Dsonar.sourceEncoding=UTF-8 \
-                  -Dsonar.organization=${ORGANIZATION} \
-                  -Dsonar.projectKey="${ORGANIZATION}_${ARTIFACT_ID}" \
-                  -Dsonar.branch.name=master
-          else
-            mvn -B versions:set -e -DnewVersion="$BRANCH_MVN_VERSION"
-            mvn -B sonar:sonar \
-                  -s $GITHUB_WORKSPACE/settings.xml \
-                  -Dsonar.token=${SONAR_TOKEN} \
-                  -Dsonar.host.url=https://sonarcloud.io \
-                  -Dsonar.sourceEncoding=UTF-8 \
-                  -Dsonar.organization=${ORGANIZATION} \
-                  -Dsonar.projectKey="${ORGANIZATION}_${ARTIFACT_ID}" \
-                  -Dsonar.branch.name=${BRANCH_NAME} \
-                  -Dsonar.branch.target=master
-          fi   
+      
           
   analyze:
     runs-on: ubuntu-latest
-    needs: build
+    needs: [build,setup]
     
     permissions:
       contents: read
@@ -230,4 +183,53 @@ jobs:
         with:
           files: |
             ./target/surefire-reports/TEST-*.xml
-            ./target/failsafe-reports/TEST-*.xml    
+            ./target/failsafe-reports/TEST-*.xml   
+            
+      # TODO: MOVE TO SEPARATE JOB. SEE TICKET https://github.com/dboeckli/spring-6-project-template/issues/26
+      - name: analyze
+        env:
+          GITHUB_ACTOR: ${{ github.actor }}
+          GITHUB_TOKEN: ${{ github.token }}
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+          BRANCH_MVN_VERSION: ${{needs.setup.outputs.BRANCH_MVN_VERSION}}
+          BRANCH_NAME: ${{needs.setup.outputs.BRANCH_NAME}}
+          DOCKER_USER: ${{ secrets.DOCKER_USER }}
+          DOCKER_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
+          ORGANIZATION: ${{needs.setup.outputs.ORGANIZATION}}
+          ARTIFACT_ID: ${{needs.setup.outputs.ARTIFACT_ID}}
+        
+        run: |
+          set -o pipefail    # don't hide errors within pipes
+          set -o nounset     # abort on unbound variable
+          set -o errexit     # abort on nonzero exit status
+          
+          # Check if required parameters are set
+          required_params=("SONAR_TOKEN")
+          for param in "${required_params[@]}"; do
+            if [ -z "${!param}" ]; then
+              echo "::error::Required parameter $param is not set"
+              exit 1
+            fi
+          done
+          
+          if [[ "${BRANCH_NAME}" == "master" ||  "${BRANCH_NAME}" == "main" ]]; then
+            mvn -B sonar:sonar \
+                  -s $GITHUB_WORKSPACE/settings.xml \
+                  -Dsonar.token=${SONAR_TOKEN} \
+                  -Dsonar.host.url=https://sonarcloud.io \
+                  -Dsonar.sourceEncoding=UTF-8 \
+                  -Dsonar.organization=${ORGANIZATION} \
+                  -Dsonar.projectKey="${ORGANIZATION}_${ARTIFACT_ID}" \
+                  -Dsonar.branch.name=master
+          else
+            mvn -B versions:set -e -DnewVersion="$BRANCH_MVN_VERSION"
+            mvn -B sonar:sonar \
+                  -s $GITHUB_WORKSPACE/settings.xml \
+                  -Dsonar.token=${SONAR_TOKEN} \
+                  -Dsonar.host.url=https://sonarcloud.io \
+                  -Dsonar.sourceEncoding=UTF-8 \
+                  -Dsonar.organization=${ORGANIZATION} \
+                  -Dsonar.projectKey="${ORGANIZATION}_${ARTIFACT_ID}" \
+                  -Dsonar.branch.name=${BRANCH_NAME} \
+                  -Dsonar.branch.target=master
+          fi           
