improve helm template

diff --git a/.github/workflows/maven-build.yml b/.github/workflows/maven-build.yml
--- a/.github/workflows/maven-build.yml
+++ b/.github/workflows/maven-build.yml
@@ -341,6 +341,14 @@ jobs:
           NAMESPACE: ${{needs.build.outputs.NAMESPACE}}
 
         run: |
+          # Check if required parameters are set
+          required_params=("BRANCH_MVN_VERSION" "HELM_CHART_VERSION" "NAMESPACE" "GH_TOKEN")
+          for param in "${required_params[@]}"; do
+            if [ -z "${!param}" ]; then
+              echo "::error::Required parameter $param is not set"
+              exit 1
+            fi
+          done
           echo "Trigger Deployment with variables"
           echo "BRANCH_MVN_VERSION: $BRANCH_MVN_VERSION"
           echo "HELM_CHART_VERSION: $HELM_CHART_VERSION"
@@ -348,6 +356,8 @@ jobs:
           
           gh workflow run deploy-and-test-cluster.yml -R ${{ github.repository }} -r ${{ github.ref }} \
           -f "version=$BRANCH_MVN_VERSION" \
+          -f "helm-chart-version=$HELM_CHART_VERSION" \
+          -f "namespace=$NAMESPACE" \
           -f "deployed-by-build=${{ github.run_id }}" \
           -f "deployed-by-workflow=${{ github.workflow }}"
 
