Feature/initial setup (#1)
* fix project

* remove kafka

* add todos for template

* fail build when missing parameter

diff --git a/.github/workflows/maven-build.yml b/.github/workflows/maven-build.yml
--- a/.github/workflows/maven-build.yml
+++ b/.github/workflows/maven-build.yml
@@ -103,6 +103,16 @@ jobs:
           set -o pipefail    # don't hide errors within pipes
           set -o nounset     # abort on unbound variable
           set -o errexit     # abort on nonzero exit status
+          
+          # Check if required parameters are set
+          required_params=("GITHUB_ACTOR" "GITHUB_TOKEN" "BRANCH_MVN_VERSION" "BRANCH_NAME" "DOCKER_USER" "DOCKER_TOKEN")
+          for param in "${required_params[@]}"; do
+            if [ -z "${!param}" ]; then
+              echo "::error::Required parameter $param is not set"
+              exit 1
+            fi
+          done
+          
           if [[ "${BRANCH_NAME}" == "master" ]]; then
             echo "::notice:: ### Build of Master. Version: $BRANCH_MVN_VERSION"
           else
