Feature/add helm charts (#60)
fix helm deployment

diff --git a/.github/workflows/maven-build.yml b/.github/workflows/maven-build.yml
--- a/.github/workflows/maven-build.yml
+++ b/.github/workflows/maven-build.yml
@@ -205,22 +205,22 @@ jobs:
         run: |
           set -o pipefail    # don't hide errors within pipes
           set -o nounset     # abort on unbound variable
-          set -o errexit     # abort on nonzero exit status
+          set -o errexit     # abort on nonzero exit status 
           
           HELM_CHART_VERSION=$(grep 'helm.chart.version' target/helm.properties | cut -d'=' -f2)
           echo "### helm chart version is: $HELM_CHART_VERSION"
           echo "HELM_CHART_VERSION=$HELM_CHART_VERSION" >> $GITHUB_OUTPUT
           
-          NAMESPACE=$(grep 'name:' target/helm-templated/$ARTIFACT_ID/templates/namespace.yaml | awk '{print $2}')
+          NAMESPACE=$(grep 'name:' target/helm-templated/$ARTIFACT_ID/templates/namespace.yaml | awk '{print $2}') 
           if [ -z "$NAMESPACE" ]; then
             NAMESPACE="default"
           fi
           echo "### namespace is: $NAMESPACE"
-          echo "NAMESPACE=$NAMESPACE" >> $GITHUB_OUTPUT
+          echo "NAMESPACE=$NAMESPACE" >> $GITHUB_OUTPUT 
           
           echo ":sailboat: Helm Chart Version: $HELM_CHART_VERSION" >> $GITHUB_STEP_SUMMARY
           echo ":sailboat: Namespace: $NAMESPACE" >> $GITHUB_STEP_SUMMARY
-          
+
   analyze:
     runs-on: ubuntu-latest
     needs: [ setup ]
@@ -344,22 +344,16 @@ jobs:
           BRANCH_MVN_VERSION: ${{needs.setup.outputs.BRANCH_MVN_VERSION}}
           HELM_CHART_VERSION: ${{needs.build.outputs.HELM_CHART_VERSION}}
           NAMESPACE: ${{needs.build.outputs.NAMESPACE}}
-
+          ARTIFACT_ID: ${{needs.setup.outputs.ARTIFACT_ID}}
         run: |
-          # Check if required parameters are set
-          required_params=("BRANCH_MVN_VERSION" "HELM_CHART_VERSION" "NAMESPACE" "GH_TOKEN")
-          for param in "${required_params[@]}"; do
-            if [ -z "${!param}" ]; then
-              echo "::error::Required parameter $param is not set"
-              exit 1
-            fi
-          done
           echo "Trigger Deployment with variables"
+          echo "ARTIFACT_ID: $ARTIFACT_ID"
           echo "BRANCH_MVN_VERSION: $BRANCH_MVN_VERSION"
           echo "HELM_CHART_VERSION: $HELM_CHART_VERSION"
           echo "NAMESPACE: $NAMESPACE"
           
           gh workflow run deploy-and-test-cluster.yml -R ${{ github.repository }} -r ${{ github.ref }} \
+          -f "application-name=$ARTIFACT_ID" \
           -f "version=$BRANCH_MVN_VERSION" \
           -f "helm-chart-version=$HELM_CHART_VERSION" \
           -f "namespace=$NAMESPACE" \
