trigger deployment after success

diff --git a/.github/workflows/maven-build.yml b/.github/workflows/maven-build.yml
--- a/.github/workflows/maven-build.yml
+++ b/.github/workflows/maven-build.yml
@@ -39,6 +39,27 @@ jobs:
           server-id: github # Value of the distributionManagement/repository/id field of the pom.xml.
           settings-path: ${{ github.workspace }} # location for the settings.xml file
 
+      - name: Verify Variables and Secrets
+        run: |
+          required_vars=("DOCKER_USER" "CI_USER" "CI_USER_EMAIL")
+          required_secrets=("DOCKER_ACCESS_TOKEN" "SONAR_TOKEN" "TRIGGER_WORKFLOW_TOKEN" "RELEASE_TOKEN")
+          
+          for var in "${required_vars[@]}"; do
+            if [ -z "${{ vars[var] }}" ]; then
+              echo "::error::Required variable $var is not set"
+              exit 1
+            fi
+          done
+          
+          for secret in "${required_secrets[@]}"; do
+            if [ -z "${{ secrets[secret] }}" ]; then
+              echo "::error::Required secret $secret is not set"
+              exit 1
+            fi
+          done
+          
+          echo "All required variables and secrets are set."
+
       - name: Set Maven Versions
         id: set_version
         env:
@@ -59,6 +80,19 @@ jobs:
           echo "### ALLMYSECRETS: $ALLMYSECRETS"
           echo "### ALLMYVARS: $ALLMYVARS"
           echo "### ALLMYOUTPUT: $ALLMYOUTPUT"
+          
+          # Verify required outputs from set_version step
+          required_outputs=("BRANCH_MVN_VERSION" "BRANCH_NAME" "MVN_VERSION" "ARTIFACT_ID" "GROUP_ID" "ORGANIZATION")
+          for output in "${required_outputs[@]}"; do
+            value="${{ steps.set_version.outputs[output] }}"
+            if [ -z "$value" ]; then
+              echo "::error::Required output $output is not set"
+              exit 1
+            else
+              echo "$output is set to: $value"
+            fi
+          done
+          
           echo ":sunflower: Cleaned Branch Name: ${{ steps.set_version.outputs.BRANCH_NAME }}" >> $GITHUB_STEP_SUMMARY
           echo ":maple_leaf: ORGANIZATION: ${{ steps.set_version.outputs.ORGANIZATION }}" >> $GITHUB_STEP_SUMMARY
           echo ":maple_leaf: GROUP ID: ${{ steps.set_version.outputs.GROUP_ID }}" >> $GITHUB_STEP_SUMMARY
@@ -250,6 +284,7 @@ jobs:
   Trigger-Deploy:
     runs-on: ubuntu-latest
     needs: [ setup, build ]
+    if: github.event_name != 'pull_request'
 
     permissions:
       actions: write
